; ============================
; Xdebug Config - Development
; ============================
zend_extension=xdebug

; Hanya aktif jika PHP_ENABLE_XDEBUG=1
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.log_level=0
xdebug.log=/tmp/xdebug.log
